### ISSUE TITLE
Can you give an example of how to use with webpackDevServer?

### ISSUE THREAD

**Issue by davidblurton** [gaearon/react-transform-boilerplate#104]

**Comment by sorahn** [comment]
+1.  Works exactly as described with the dev-middleware, but so far I've been unable to just get webpack dev server to work it's magic.

**Comment by marr** [comment]
Is this repo still maintained? I'm curious where people are finding best-in-breed boilerplates with w-d-s and react. I'd like to try koa and server-rendering, and some snappy tests (jsdom, enzyme, not karma). Is that worthy of yet another boilerplate repo or could it be done with this one?

**Comment by gaearon** [comment]
Since I would prefer not to maintain two boilerplates, and WDS is problematic for people using server rendering, I would prefer not to do that.

>Is this repo still maintained? I'm curious where people are finding best-in-breed boilerplates with w-d-s and react. I'd like to try koa and server-rendering, and some snappy tests (jsdom, enzyme, not karma). Is that worthy of yet another boilerplate repo or could it be done with this one?

The only reason this repo exists is to show how to configure React Transform in an empty project. It isn’t meant to keep up with latest libraries, “best practices”, etc. In fact this is explicitly a non-goal for this project. You are, however, welcome to use it to see the minimal configuration necessary for React Transform to work, and to use that knowledge for creating your own boilerplate with the scope you deem necessary.

Cheers!
