### ISSUE TITLE
github archive doesn't contain .babelrc

### ISSUE THREAD

**Issue by lalop** [gaearon/react-transform-boilerplate#112]
Hello,

I give a try to react-transform-boilert-plate by downloading the zip from github but the archive dosn't contain the `.babelrc` file so `npm start` result in this error :

```
Module build failed: SyntaxError: /.../src/index.js: Unexpected token (5:7)
  3 | import { App } from './App';
  4 | 
> 5 | render(<App />, document.getElementById('root'));
    |        ^
  6 | 
```

I don't know if that can be fixed but maybe that can be noticed in the Readme

**Comment by gaearon** [comment]
Please feel free to send a PR to README to document this. The same is also true for any boilerplate project on GitHub, and since pretty much all of them contain `.babelrc` nowadays so it is not really unique. In fact this boilerplate is pretty experimental and is targeted at people who are deeply familiar with React and Webpack, so I would assume the target audience is already familiar with less experimental boilerplates and that’s why I don’t see this as a big problem.
