### ISSUE TITLE
If "full reload needed" does this need to be manually?

### ISSUE THREAD

**Issue by donaldpipowitch** [gaearon/react-transform-boilerplate#120]
Hi, sorry I can't find this in the docs or somewhere else, but if I get the "The following modules couldn't be hot updated: (Full reload needed)" message, can I make this full reload automatically somehow? It seems like a step backwards to add hot and live reloading everywhere, but reload manually for non-components :)

**Comment by gaearon** [comment]
Webpack hot module updates follow the import chain. As long as a module “ends up” being imported from components only, hot updates will work. If a specific module import chain ends in something like `index.js` which is not a component, hot updates will fail because `react-transform-hmr` has no idea how to handle updates to something other than components.

That said you can write manual code to handle hot updates of modules that don’t end up consumed by components. For example, this is how [we hot replace reducers in Redux](https://github.com/reactjs/redux/blob/952b45d6d74f1789ddc4ed05043a2c6e1a5ea808/examples/async/store/configureStore.js#L13-L19).

**Comment by tedpennings** [comment]
Is there a way to plugin to the React HMR features to extend it and make it aware of my code? 

I'm working on code that reads config in JSON and creates React elements on the fly, so the HMR proxying doesn't work. I basically have a top-level function that returns a React Router element, which delegates to functions that create React component classes through currying. 

If this use case isn't a good fit for React HMR, that's a totally reasonable answer -- I've considered implementing json config->React app as a compile-time transform (probably as a webpack loader for the JSON config file).

**Comment by gaearon** [comment]
Do you care about preserving component local state (`this.state`) on hot reloads? If not, just don’t use proxying and use raw HMR API to replace the whole component subtree with a new version [like here](https://github.com/reactjs/redux/pull/1455).

**Comment by tedpennings** [comment]
Oh that's awesome and exactly what I need, thanks!

**Comment by donaldpipowitch** [comment]
Thank you for your answer.
