### ISSUE TITLE
Errors from React's render() function are not being shown

### ISSUE THREAD

**Issue by Dharmoslap** [gaearon/react-transform-boilerplate#50]
The only main difference between my setup and react-transform-boilerplate i that I'm using updated packges:
"babel-core": "^5.8.25",
"babel-loader": "^5.3.2",
"react-transform-hmr": "^1.0.1",
"redbox-react": "^1.1.1",
"webpack": "^1.12.2",
"webpack-dev-middleware": "^1.2.0",
"webpack-hot-middleware": "^2.4.1",
 "react": "^0.14.0"

I'm also using webpack multiple entry points (https://webpack.github.io/docs/multiple-entry-points.html), but that shouldn't cause any problem.

**Comment by Dharmoslap** [comment]
You can check my code and reproduce the bug here: https://bitbucket.org/ladislavmaxa/redux-debug

**Comment by josephfinlayson** [comment]
I'm seeing something like this also.

**Comment by gaearon** [comment]
I'm currently busy with Egghead videos for Redux so I won't be able to take a look at this for a few more weeks. Please be patient.

**Comment by josephfinlayson** [comment]
:+1: Thanks!

**Comment by Dharmoslap** [comment]
Alright, let's wait for this.

**Comment by Dharmoslap** [comment]
How is it now?

**Comment by deathmood** [comment]
I've got similar issue. Suppose you have:

```js

const style = {
  color: red       // yes, it should be 'red'
};


class App extends ....
```

There is no message shown in browser window - although when I switch to chrome dev tools I see `Uncaught ReferenceError: red is not defined`

**Comment by gaearon** [comment]
So, as for the original issue report, this is the expected behavior.
This boilerplate catches two types of errors:

* Runtime errors *inside* `render()`
* Syntax errors

Specifying `style` as a string rather than as an object is neither—it's just a wrong return value. React *will* throw later, but internally, and this is not something we can handle.

-----------------------------

@deathmood 

In your case, this is also the expected behavior. We don't catch runtime errors at *module definition*. Only inside `render()`.
