### ISSUE TITLE
Components not reloading

### ISSUE THREAD

**Issue by gnudle** [gaearon/react-transform-boilerplate#89]
Hi, is something broken with the current build? 

The components display and it says HMR connected in the console but there is no hot reload (even after page refresh).   

I tried adding 'webpack-hot-middleware/client?reload=true', to the entry, but that didn't help either.  

Running this on a Mac

**Comment by 2c2c** [comment]
same issue on windows.

to take this one step further, I've never managed to find a boilerplate that works using webpack with dev/hot middleware. i've been working around this problem because I luckily managed to make webpack-dev-server at some point work in my project, so I made as much front-end as I could without needing an actual server.

now that I need an actual server, I'm pretty much stuck :)

**Comment by mjasnikovs** [comment]
Same here, just dose not work, haw to manually reload to see changes.

**Comment by 2c2c** [comment]
solved this after many days of issues by *completely* removing node and npm and reinstalling

you should look up an OS specific guide to ensure you clean out all lingering files. fixed problem for me on windows. gl

**Comment by mjasnikovs** [comment]
I just created my own boilerplate, and and it works. I don't think there is anything OS specific, just some small bug.

**Comment by davidhouweling** [comment]
I too am having this problem... Running Windows 10 64-bit and node 4.1.1, will do as suggested above and try again.

**Comment by davidhouweling** [comment]
Looks to be more in line with this problem: https://github.com/glenjamin/webpack-hot-middleware/issues/36

**Comment by frontsideair** [comment]
I'm having the same issue, could it be this: https://github.com/webpack/webpack/issues/675

**Comment by gnudle** [comment]
Thank you!
